-- List Types: 
--
-- A list is a sequence of elements of the same type. 
--
-- 	[True, True, False] :: [Bool]
-- 	[1, 2, 4, 5, 2, 6]  :: [Int] | [Integer] | etc..
-- 	[[1, 2, 3], [3,2,5,7]] :: [[Int]]
-- 	[['1', '2', '3'], ['3','2','5','7']] :: [[Char]]
--
-- Note: Something that we'll consider later is the singleton list [[]].
-- Note: Due to lazy evaluation of, the use of infinite lists [1..] 
-- 	is encouraged if the problem suits it.
