-- Tuple Types:
--
-- A Tuple is a finite sequence of components of heterogenous types. 
-- 
-- 	( 1, "Hello, World", 'a' ) :: ( Int, String, Char )
--	( False, True ) :: ( Bool, Bool )
--	[('a', False), ('b', True)] :: [(Char, Bool)]
--	(['a', 'b'],[False, True]) :: ([Char], [Bool])
