name:                MonadTransformers
version:             0.1.0.0
github:              "OpenJ92/MonadTransformers"
license:             BSD3
author:              "Jacob Vartuli-Schonberg"
maintainer:          "jacob.vartuli.schonberg@gmail.com"
copyright:           "2021 Jacob Vartuli-Schonberg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/OpenJ92/MonadTransformers#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  MonadTransformers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MonadTransformers

tests:
  MonadTransformers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MonadTransformers
